Develop
MagicMirrorOrg/MagicMirror pull request #3125
Opened 2023-06-17 00:03 UTC by JasonStieber

Pull request fixes small big in weathergov api format mismatch #3124

2023-06-17 17:09 UTC, rejas requested changes

2023-06-17 17:09 UTC, rejas commented on modules/default/weather/providers/weathergov.js
> +		currentWeather.precipitationAmount = currentWeatherData.precipitationLast3Hours.value;
Maybe use the 3hours info as a fallback in case the precipitationLastHour is undefined?

2023-07-13 05:37 UTC, rejas commented on package.json
> +		"electron": "^25.2.0",
electron should stay in the optional dependencies

2023-09-09 21:08 UTC, khassel commented
@JasonStieber can you make the requested changes?

2024-01-18 11:07 UTC, rejas commented
pinging @JasonStieber in the hope he picks this PR up again

2024-06-22 20:43 UTC, khassel commented
Looking into the data getting from the weather gov api there is still a property `precipitationLastHour`:

![grafik](https://github.com/MagicMirrorOrg/MagicMirror/assets/25914086/8ce65d8e-477f-4a51-a16e-faf276273423)

@rejas So we could implement a logical change to use `precipitationLast3Hours` if `precipitationLastHour` is `null` or close this PR.

2024-06-24 20:20 UTC, rejas commented
> @rejas So we could implement a logical change to use `precipitationLast3Hours` if `precipitationLastHour` is `null` or close this PR.

I would vote for the logical change. And you and @sdetweil ?

2024-06-27 21:22 UTC, khassel commented
> I would vote for the logical change.

I implemented this now.

2024-06-28 20:10 UTC, rejas approved these changes

2024-06-28 20:21 UTC, merged