Fix issue 3393
MagicMirrorOrg/MagicMirror pull request #3395
Opened 2024-03-07 19:05 UTC by jkriegshauser

Fix for #3393

2024-03-12 17:07 UTC, jkriegshauser commented
@khassel @rejas review please?

2024-03-13 06:32 UTC, rejas requested changes

2024-03-13 06:32 UTC, rejas commented on tests/configs/modules/calendar/rrule_until.js
> +/* MagicMirror² Test calendar exdate
those header are not necessary anymore

2024-03-13 06:53 UTC, rejas commented
sorry for the long delay, lots of life stuff. only a small request change

2024-03-13 15:16 UTC, jkriegshauser commented on tests/configs/modules/calendar/rrule_until.js
> +/* MagicMirror² Test calendar exdate
Alright, removed the header there

2024-03-13 19:59 UTC, rejas approved these changes

2024-03-13 19:59 UTC, merged