Fix crash possibility if `module: <name>` is not defined
MagicMirrorOrg/MagicMirror pull request #3445
Opened 2024-05-10 12:28 UTC by bugsounet

Fix #3442

2024-05-13 09:09 UTC, KristjanESPERANTO commented
Just a thought: Wouldn't that be a thing that belongs in `check_config.js`?

2024-05-13 16:53 UTC, bugsounet commented
`check_config.js` check only syntax but it does not check the contents of the file

should we make some other checks on it too ?

2024-05-13 17:07 UTC, sdetweil commented
well, this one is the first actual content that is important.. 
altho position  should be checked too.. at least valid if specified.. that is another crash..

2024-05-13 17:15 UTC, bugsounet commented
So, we have to check `module: <name>`and `position: <valid position>` (if defined)

we check it on `check_config.js` and MM core ?

2024-05-13 17:22 UTC, sdetweil commented
I think so.. never crash..

2024-05-13 17:24 UTC, bugsounet commented
ok, I will see to code it

2024-05-17 17:37 UTC, bugsounet commented
Right, I will try to add needed rules with eslint in `check_config.js` ;)

I have never done this kind of test.
bugsounet, it's time to learn :)

2024-05-18 12:14 UTC, bugsounet commented
module name error:
![image](https://github.com/MagicMirrorOrg/MagicMirror/assets/30669209/a16f4999-3b06-47b1-ad79-0db86fb8aa51)

postion error:
![image](https://github.com/MagicMirrorOrg/MagicMirror/assets/30669209/52c4db51-e8f4-4be8-87ea-82d219da349b)

No error:
![image](https://github.com/MagicMirrorOrg/MagicMirror/assets/30669209/8377cf56-a171-4f55-8de3-82edbe0f8c93)

I'm not sure that i can integrate it into eslint

2024-06-01 15:38 UTC, bugsounet commented
Before approuve some new deps.
Thanks to review this :>

2024-06-07 21:24 UTC, khassel commented
If I use a module with a valid position and `disabled: true` , e.g.

```js
		{
			module: "weather",
			header: "default weather module current",
			position: "top_left",
			disabled: true,
			config: {
				weatherProvider: "openmeteo",
				lat: 50.17659,
				lon: 8.62685,
				useCorsProxy: true,
				roundTemp: true,
				showPrecipitationProbability: true,
				showHumidity: "wind",
				showUVIndex: true,
				appendLocationNameToHeader: false,
				windUnits: "kmh",
				showFeelsLike: false,
				bridgeId: "abc",
			},
		},
```

I get a warning

```bash
[2024-06-07 23:21:00.091] [WARN]  No module name found for this configuration: {
  module: 'weather',
  header: 'default weather module current',
  position: 'top_left',
  disabled: true,
  config: {
    weatherProvider: 'openmeteo',
    lat: 50.17659,
    lon: 8.62685,
    useCorsProxy: true,
    roundTemp: true,
    showPrecipitationProbability: true,
    showHumidity: 'wind',
    showUVIndex: true,
    appendLocationNameToHeader: false,
    windUnits: 'kmh',
    showFeelsLike: false,
    bridgeId: 'abc'
  }
}
```

Is this intended? I think we need no such warning for disabled modules ...

2024-06-08 02:27 UTC, sdetweil commented
i agree, no warning there.

2024-06-08 11:42 UTC, bugsounet commented
sure, it's not logical

2024-06-08 12:01 UTC, bugsounet commented
fixed

2024-06-08 18:31 UTC, khassel approved these changes

2024-06-08 20:11 UTC, rejas requested changes

2024-06-08 20:11 UTC, rejas commented on js/loader.js
> +	const positions = ["top_bar", "top_left", "top_center", "top_right", "upper_third", "middle_center", "lower_third", "bottom_left", "bottom_center", "bottom_right", "bottom_bar", "fullscreen_above",
this code seems double, can we put it in a common class?

2024-06-08 20:11 UTC, rejas commented on js/loader.js
> +		const AllModules = config.modules.filter((module) => (module.module !== undefined) && (positions.indexOf(module.position) > -1 || typeof (module.position) === "undefined"));
part of this code seems double, can we put it in a common function?

2024-06-11 16:42 UTC, bugsounet commented
![image](https://github.com/MagicMirrorOrg/MagicMirror/assets/30669209/78ee2b14-f180-416a-87cc-22a833d91aab)

It's boring to redo the packages :/

2024-06-20 14:38 UTC, bugsounet commented
ping @rejas

2024-06-22 19:25 UTC, rejas reviewed
ping @bugsounet

2024-06-22 19:25 UTC, rejas commented on js/loader.js
> +		const positions = ["top_bar", "top_left", "top_center", "top_right", "upper_third", "middle_center", "lower_third", "bottom_left", "bottom_center", "bottom_right", "bottom_bar", "fullscreen_above",
cant we put these positions (used also in app.js) in a common file)?

2024-06-23 12:18 UTC, bugsounet commented
@rejas: 

* I see that postions is again used in main.js. So I use it with MM.getAvailableModulePositions
 --> I able to have all position in loader.js

* I have move *position* utils in utils.js
 --> used in app.js with Utils.moduleHasValidPosition()

2024-06-24 17:31 UTC, bugsounet commented
@rejas: tell me

 * If it's ok for you or not ?
 * If you want really push it for MM² v2.28 ?
 
Sorry to say this but it's discouraging (this PR is open since May 10)  :/

2024-06-24 19:51 UTC, rejas commented
> @rejas: tell me
> 
>     * If it's ok for you or not ?
> 
>     * If you want really push it for MM² v2.28 ?
> 
> 
> Sorry to say this but it's discouraging (this PR is open since May 10) :/

Of course its ok for me (I do trust your code :-) I was jsut pondering a lot if we could move ALL the position usages into the same file. but that would be as we say in germany: in schönheit sterben (meaning "to die in beauty" aka to work too much and never finish :-D

So sorry for my slow approbval, but will do now!

2024-06-24 19:51 UTC, rejas approved these changes

2024-06-24 19:51 UTC, merged