Bug in Weather Units for Broadcasted Notification
MagicMirrorOrg/MagicMirror pull request #3519
Opened 2024-08-04 19:41 UTC by skpanagiotis

This PR resolve Issue number #3419 .

I have added the method `convertWeatherObjectToImperial()` which converts the units of the `notificationPayload `to imperial if needed, in order to pass the object in `sendNotification()`.

2024-08-04 20:15 UTC, khassel commented
Thanks! Can you please add an entry to the `CHANGELOG.md` file? (otherwise the tests will fail ...)

2024-08-04 21:17 UTC, khassel commented
if you need help to fix the lint errors in the failed test let me know

2024-08-04 22:13 UTC, sdetweil commented
Some of the problem is doing npm run install-mm doesn’t install the git commit hooks

2024-08-05 19:21 UTC, skpanagiotis commented
I resolve eslint errors.
Is there a possibility that the failed tests are due to my code?

2024-08-05 19:32 UTC, khassel commented
yes, you introduced `const WeatherObject = require("./weatherobject");` but in the tests we have in file `weather_object_spec.js` the same variable name `const WeatherObject = require ...` so renaming one of them should solve this

2024-08-05 20:38 UTC, skpanagiotis commented
Thanks very much for your time and help, my mistake is that I skipped running tests, because I was working on Windows system.

2024-08-05 20:59 UTC, rejas requested changes

2024-08-05 20:59 UTC, rejas commented on modules/default/weather/weatherutils.js
> +	 * @param {string} unit can be "imperial" or 'metric'
these quote changes should be reverted

2024-08-05 20:59 UTC, rejas commented on modules/default/weather/weatherutils.js
> +	 * @param {string} unit can be 'beaufort', 'kmh', 'knots, "imperial" (mph)
these ones too

2024-08-06 07:04 UTC, rejas requested changes

2024-08-18 07:52 UTC, rejas commented on modules/default/weather/weatherutils.js
> +		else return value * 0.03937007874;
sorry for late reply... 

about cm vs mm: is there some hint that "cm" is used somewhere in the response? weather provider use mm in their data almost exclusivly....

2024-08-18 07:58 UTC, rejas approved these changes

2024-08-18 07:58 UTC, rejas commented on modules/default/weather/weatherutils.js
> +		else return value * 0.03937007874;
sorry for late reply and my first wrong response...

i get your point, will add a small improvement myself and approve

2024-08-18 08:04 UTC, merged